### ISSUE TITLE
NVL .glsl shader for `mpv`?

### ISSUE THREAD

**Issue by kvnxiao** [funnyplanter/CuNNy#5]
Since mpv supports rendering static images, it would be also great to have the `NVL` variant for mpv in `.glsl` format!

**Comment by funnyplanter** [comment]
I've ported the generation code as a webapp and mpv generator to work with NVL now: https://funnyplanter.github.io/

**Comment by kvnxiao** [comment]
Going to close this issue as done since the online generator can help generate mpv .glsl shaders. But going to keep https://github.com/funnyplanter/CuNNy/issues/4 open since it'll still need a WebGL / WebGPU compatible shader
